name: Budget Guardrail

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  guardrail:
    runs-on: ubuntu-latest
    name: Run Budget Guardrail
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Run budget guardrail
        env:
          # Allow repo variables BUDGET_PROD or BUDGET to override the CLI budget
          BUDGET_PROD: ${{ vars.BUDGET_PROD }}
          BUDGET: ${{ vars.BUDGET }}
        run: |
          python scripts/section11_budget_guardrail.py --predicted-json dashboards/predicted_cost.json --budget 1000 --env prod --block-exit
        # If the script exits non-zero the job will fail, blocking the PR from merging until addressed.
